version: "3"

services:
  telegraf:
    image: telegraf:1.5.2
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/rootfs/sys:ro
      - /proc:/rootfs/proc:ro
      - /etc:/rootfs/etc:ro
    environment:
      HOST_PROC: /rootfs/proc
      HOST_SYS: /rootfs/sys
      HOST_ETC: /rootfs/etc
    hostname: "{{.Node.Hostname}}-{{.Service.Name}}"
    networks:
      - monitoring-tier
    deploy:
      mode: global

  influxdb:
    deploy:
      placement:
        constraints:
          - node.role==manager

  grafana:
    deploy:
      placement:
        constraints:
          - node.role==manager

volumes:
  influxdb-data:
  grafana-data:
    
networks:
  monitoring-tier: