version: "3"

services:
  influxdb:
    image: influxdb:1.4.3-alpine
    restart: always
    volumes:
      - "influxdb-data:/var/lib/influxdb"
      - ./influxdb.conf:/etc/influxdb/influxdb.conf
      - ./types.db:/usr/share/collectd/types.db:ro
    environment:
      - INFLUXDB_DB=telegraf
    hostname: influxdb
    networks:
      - monitoring-tier

  grafana:
    image: grafana/grafana:5.0.0
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_ROOT_URL=http://grafana.example.com
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=smtp.gmail.com:587
      - GF_SMTP_USER=alert@gmail.com
      - GF_SMTP_PASSWORD=password
      - GF_SMTP_SKIP_VERIFY=true
      - GF_SMTP_FROM_ADDRESS=alert@gmail.com
      - GF_SMTP_FROM_NAME=Grafana
    hostname: grafana
    networks:
      - monitoring-tier

volumes:
  influxdb-data:
  grafana-data:
  
networks:
  monitoring-tier: