version: "2"

services:
    mysql-1:
        image: mysql:5.7
        networks:
            - nginx-back
        volumes:
            - ./mysql-1/mysql-logs/:/var/log/mysql/
            - ./mysql-1/mysql-data/:/var/lib/mysql/
            - ./mysql-1/mysql-conf/:/etc/mysql/conf.d
            - ./mysql-1/mysql-init/:/docker-entrypoint-initdb.d
        environment:
            - MYSQL_ROOT_PASSWORD=dev@123
            - MYSQL_DATABASE=demo
        ports:
            - "3316:3306"
        hostname: mysql1
        logging:
            driver: "json-file"
            options:
                max-size: "100M"
                max-file: "3"

    mysql-2:
        image: mysql:5.7
        networks:
            - nginx-back
        volumes:
            - ./mysql-2/mysql-logs/:/var/log/mysql/
            - ./mysql-2/mysql-data/:/var/lib/mysql/
            - ./mysql-2/mysql-conf/:/etc/mysql/conf.d
            - ./mysql-2/mysql-init/:/docker-entrypoint-initdb.d
        environment:
            - MYSQL_ROOT_PASSWORD=dev@123
            - MYSQL_DATABASE=demo
        ports:
            - "3326:3306"
        hostname: mysql2
        logging:
            driver: "json-file"
            options:
                max-size: "100M"
                max-file: "3"

networks:
    nginx-back: