version: '3.8'
services:
  mongo1:
    hostname: mongo1
    container_name: local-mongo1
    image: mongo:4.2.9
    restart: always
    expose:
      - 27017
    ports:
      - 27016:27017
    command: '--quiet --bind_ip_all --replSet rs0'
    volumes:
      - mongodb-data:/data/db

  mongo2:
    hostname: mongo2
    container_name: local-mongo2
    image: mongo:4.2.9
    restart: always
    expose:
      - 27017
    ports:
      - 27018:27017
    command: '--quiet --bind_ip_all --replSet rs0'

  mongo3:
    hostname: mongo3
    container_name: local-mongo3
    image: mongo:4.2.9
    restart: always
    expose:
      - 27017
    ports:
      - 27019:27017
    command: '--quiet --bind_ip_all --replSet rs0'

  rsinit:
    build:
      context: .
      dockerfile: rsinit.Dockerfile
    volumes:
        - ./rs.sh:/app/rs.sh
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    entrypoint: ["sh", "-c", "/app/rs.sh"]

volumes:
  mongodb-data:
    