services:
  code-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: code-server:with-ssh
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PASSWORD=password #optional
      # - HASHED_PASSWORD= #optional
      # - SUDO_PASSWORD=password #optional
      # - SUDO_PASSWORD_HASH= #optional
      # - PROXY_DOMAIN=code-server.my.domain #optional
      - DEFAULT_WORKSPACE=/config/workspace #optional
    volumes:
      - ./:/config/workspace/
      - ~/.ssh/:/config/.ssh/ # then in the container, 
                              # run ssh host-user@172.17.0.1 (Linux) or 
                              # ssh host-user@host.docker.internal (MAC) 
                              # to connect to host
                              # refer to https://medium.com/cloud-native-daily/ssh-to-docker-host-from-docker-container-e8ee0965802
                              # NOTE: to enable ssh by key, you need to add ssh public key to ~/.ssh/authorized_keys
                              # refer to https://www.digitalocean.com/community/tutorials/how-to-configure-ssh-key-based-authentication-on-a-linux-server
      - /var/run/docker.sock:/var/run/docker.sock # NOTE: if permission denied, read Dockerfile to fix it
    ports:
      - 8443:8443
