services:
  code-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: code-server:with-ssh
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PASSWORD=password #optional
      # - HASHED_PASSWORD= #optional
      # - SUDO_PASSWORD=password #optional
      # - SUDO_PASSWORD_HASH= #optional
      # - PROXY_DOMAIN=code-server.my.domain #optional
      - DEFAULT_WORKSPACE=/config/workspace #optional
    volumes:
      - ./:/config/workspace/
      # - ~/.ssh/:/.ssh:ro
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8443:8443
