#
# syntax: https://docs.docker.com/compose/yml/
#

version: "3"

services:
    nginx:
        image: nginx:1.11.6
        networks:
            - internal-network
        ports:
            - 80:80
        volumes:
            - ./configs:/etc/nginx/conf.d
            - ./log:/var/log/nginx/
            - ./web:/usr/share/nginx/html:ro
        # command: /bin/bash -c "nginx -g 'daemon off;'"
        # NOTE: below command to replace VAR1 and VAR1 value, there are many other ways, reference here:
        # https://github.com/docker-library/docs/issues/496
        # NOTE: The below command is best, reference: https://github.com/docker-library/docs/issues/496#issuecomment-370452557
        # command: /bin/bash -c "envsubst '$$VAR1 $$VAR2' < /etc/nginx/conf.d/nginx.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
        command: sh -c "envsubst \"`env | awk -F = '{printf \" $$%s\", $$1}'`\" < /etc/nginx/conf.d/nginx.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
        environment:
            - VAR1=Phung
            - VAR2=Xuan Anh
        restart: always
        logging:
            driver: "json-file"
            options:
                max-size: "100M"
                max-file: "3"
        deploy:
            resources:
                limits:
                    memory: 10M

networks:
    internal-network:
